// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDu7XnqNtJGf_3fEZMbc9B2W2_1yFqk24Y',
    appId: '1:306873216025:web:ffa0a8f682a42acbc0ce88',
    messagingSenderId: '306873216025',
    projectId: 'chatapp-7e46f',
    authDomain: 'chatapp-7e46f.firebaseapp.com',
    storageBucket: 'chatapp-7e46f.appspot.com',
    measurementId: 'G-S3C2PC4KQH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC3WesIgstp9__USziWkhVLMbvjD3OMQkk',
    appId: '1:306873216025:android:91ecad695300df49c0ce88',
    messagingSenderId: '306873216025',
    projectId: 'chatapp-7e46f',
    storageBucket: 'chatapp-7e46f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAZx3Ikfxt_o7qwz3V_pYCZW6xVjqCDmWA',
    appId: '1:306873216025:ios:39618f0a41f25535c0ce88',
    messagingSenderId: '306873216025',
    projectId: 'chatapp-7e46f',
    storageBucket: 'chatapp-7e46f.appspot.com',
    iosBundleId: 'com.example.chatapplication.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAZx3Ikfxt_o7qwz3V_pYCZW6xVjqCDmWA',
    appId: '1:306873216025:ios:39618f0a41f25535c0ce88',
    messagingSenderId: '306873216025',
    projectId: 'chatapp-7e46f',
    storageBucket: 'chatapp-7e46f.appspot.com',
    iosBundleId: 'com.example.chatapplication.chatApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDu7XnqNtJGf_3fEZMbc9B2W2_1yFqk24Y',
    appId: '1:306873216025:web:3cfe1a69c6c5ed11c0ce88',
    messagingSenderId: '306873216025',
    projectId: 'chatapp-7e46f',
    authDomain: 'chatapp-7e46f.firebaseapp.com',
    storageBucket: 'chatapp-7e46f.appspot.com',
    measurementId: 'G-TW4SWPVPT1',
  );
}
